package com.psedb.model;
import java.util.HashSet;
import java.util.Set;

/**
 * LuAccessLevel generated by hbm2java
 */
public class LuAccessLevel implements java.io.Serializable {

	private Byte accessId;
	private String accessLevel;
	private String acessDescription;
	private Set staffs = new HashSet(0);

	public LuAccessLevel() {
	}

	public LuAccessLevel(String accessLevel, String acessDescription, Set staffs) {
		this.accessLevel = accessLevel;
		this.acessDescription = acessDescription;
		this.staffs = staffs;
	}
        
        public LuAccessLevel(Byte accessId) {
		this.accessId = accessId;
	}
        
        public LuAccessLevel(Byte accessId, String acessDescription) {
		this.accessId = accessId;
                this.acessDescription = acessDescription;
	}

	public Byte getAccessId() {
		return this.accessId;
	}

	public void setAccessId(Byte accessId) {
		this.accessId = accessId;
	}

	public String getAccessLevel() {
		return this.accessLevel;
	}

	public void setAccessLevel(String accessLevel) {
		this.accessLevel = accessLevel;
	}

	public String getAcessDescription() {
		return this.acessDescription;
	}

	public void setAcessDescription(String acessDescription) {
		this.acessDescription = acessDescription;
	}

	public Set getStaffs() {
		return this.staffs;
	}

	public void setStaffs(Set staffs) {
		this.staffs = staffs;
	}

}
