package com.psedb.model;
import java.util.HashSet;
import java.util.Set;

/**
 * LuDegreeType generated by hbm2java
 */
public class LuDegreeType implements java.io.Serializable {

	private Byte degreeTypeId;
	private String dtname;
	private Set studentDegrees = new HashSet(0);

	public LuDegreeType() {
	}

	public LuDegreeType(String dtname, Set studentDegrees) {
		this.dtname = dtname;
		this.studentDegrees = studentDegrees;
	}

	public Byte getDegreeTypeId() {
		return this.degreeTypeId;
	}

	public void setDegreeTypeId(Byte degreeTypeId) {
		this.degreeTypeId = degreeTypeId;
	}

	public String getDtname() {
		return this.dtname;
	}

	public void setDtname(String dtname) {
		this.dtname = dtname;
	}

	public Set getStudentDegrees() {
		return this.studentDegrees;
	}

	public void setStudentDegrees(Set studentDegrees) {
		this.studentDegrees = studentDegrees;
	}

}
