package com.psedb.model;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StudentDegree generated by hbm2java
 */
public class StudentDegree implements java.io.Serializable {

	private Integer studentDegreeId;
	private Student student;
	private LuDegreeType luDegreeType;
	private LuThesisStatus luThesisStatus;
	private Date dateEnrolled;
	private Date dateCompleted;
	private String scholarship;
	private Date dateThesisIntendSubmit;
	private Date dateThesisSubmit;
	private String thesisTitle;
	private Date dateConfirmationIntended;
	private Date dateConfirmationCompleted;
	private Set studentComments = new HashSet(0);
	private Set studentSupervisors = new HashSet(0);
        private Byte staffId;

    public Byte getStaffId() {
        return staffId;
    }

    public void setStaffId(Byte staffId) {
        this.staffId = staffId;
    }

	public StudentDegree() {
	}

	public StudentDegree(Student student, LuThesisStatus luThesisStatus) {
		this.student = student;
		this.luThesisStatus = luThesisStatus;
	}

	public StudentDegree(Student student, LuDegreeType luDegreeType,
			LuThesisStatus luThesisStatus, Date dateEnrolled,
			Date dateCompleted, String scholarship,
			Date dateThesisIntendSubmit, Date dateThesisSubmit,
			String thesisTitle, Date dateConfirmationIntended,
			Date dateConfirmationCompleted, Set studentComments,
			Set studentSupervisors) {
		this.student = student;
		this.luDegreeType = luDegreeType;
		this.luThesisStatus = luThesisStatus;
		this.dateEnrolled = dateEnrolled;
		this.dateCompleted = dateCompleted;
		this.scholarship = scholarship;
		this.dateThesisIntendSubmit = dateThesisIntendSubmit;
		this.dateThesisSubmit = dateThesisSubmit;
		this.thesisTitle = thesisTitle;
		this.dateConfirmationIntended = dateConfirmationIntended;
		this.dateConfirmationCompleted = dateConfirmationCompleted;
		this.studentComments = studentComments;
		this.studentSupervisors = studentSupervisors;
	}

	public Integer getStudentDegreeId() {
		return this.studentDegreeId;
	}

	public void setStudentDegreeId(Integer studentDegreeId) {
		this.studentDegreeId = studentDegreeId;
	}

	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	public LuDegreeType getLuDegreeType() {
		return this.luDegreeType;
	}

	public void setLuDegreeType(LuDegreeType luDegreeType) {
		this.luDegreeType = luDegreeType;
	}

	public LuThesisStatus getLuThesisStatus() {
		return this.luThesisStatus;
	}

	public void setLuThesisStatus(LuThesisStatus luThesisStatus) {
		this.luThesisStatus = luThesisStatus;
	}

	public Date getDateEnrolled() {
		return this.dateEnrolled;
	}

	public void setDateEnrolled(Date dateEnrolled) {
		this.dateEnrolled = dateEnrolled;
	}

	public Date getDateCompleted() {
		return this.dateCompleted;
	}

	public void setDateCompleted(Date dateCompleted) {
		this.dateCompleted = dateCompleted;
	}

	public String getScholarship() {
		return this.scholarship;
	}

	public void setScholarship(String scholarship) {
		this.scholarship = scholarship;
	}

	public Date getDateThesisIntendSubmit() {
		return this.dateThesisIntendSubmit;
	}

	public void setDateThesisIntendSubmit(Date dateThesisIntendSubmit) {
		this.dateThesisIntendSubmit = dateThesisIntendSubmit;
	}

	public Date getDateThesisSubmit() {
		return this.dateThesisSubmit;
	}

	public void setDateThesisSubmit(Date dateThesisSubmit) {
		this.dateThesisSubmit = dateThesisSubmit;
	}

	public String getThesisTitle() {
		return this.thesisTitle;
	}

	public void setThesisTitle(String thesisTitle) {
		this.thesisTitle = thesisTitle;
	}

	public Date getDateConfirmationIntended() {
		return this.dateConfirmationIntended;
	}

	public void setDateConfirmationIntended(Date dateConfirmationIntended) {
		this.dateConfirmationIntended = dateConfirmationIntended;
	}

	public Date getDateConfirmationCompleted() {
		return this.dateConfirmationCompleted;
	}

	public void setDateConfirmationCompleted(Date dateConfirmationCompleted) {
		this.dateConfirmationCompleted = dateConfirmationCompleted;
	}

	public Set getStudentComments() {
		return this.studentComments;
	}

	public void setStudentComments(Set studentComments) {
		this.studentComments = studentComments;
	}

	public Set getStudentSupervisors() {
		return this.studentSupervisors;
	}

	public void setStudentSupervisors(Set studentSupervisors) {
		this.studentSupervisors = studentSupervisors;
	}

}
