package com.psedb.model;
import java.util.Date;

/**
 * StudentComment generated by hbm2java
 */
public class StudentComment implements java.io.Serializable {

	private Integer studentCommentId;
	private Staff staff;
	private StudentDegree studentDegree;
	private Date cdate;
	private String acomment;

	public StudentComment() {
	}

	public StudentComment(Staff staff, StudentDegree studentDegree) {
		this.staff = staff;
		this.studentDegree = studentDegree;
	}

	public StudentComment(Staff staff, StudentDegree studentDegree, Date cdate,
			String acomment) {
		this.staff = staff;
		this.studentDegree = studentDegree;
		this.cdate = cdate;
		this.acomment = acomment;
	}

	public Integer getStudentCommentId() {
		return this.studentCommentId;
	}

	public void setStudentCommentId(Integer studentCommentId) {
		this.studentCommentId = studentCommentId;
	}

	public Staff getStaff() {
		return this.staff;
	}

	public void setStaff(Staff staff) {
		this.staff = staff;
	}

	public StudentDegree getStudentDegree() {
		return this.studentDegree;
	}

	public void setStudentDegree(StudentDegree studentDegree) {
		this.studentDegree = studentDegree;
	}

	public Date getCdate() {
		return this.cdate;
	}

	public void setCdate(Date cdate) {
		this.cdate = cdate;
	}

	public String getAcomment() {
		return this.acomment;
	}

	public void setAcomment(String acomment) {
		this.acomment = acomment;
	}

}
